version: '3.7'

services:
  php-apache:
    depends_on:
      - db
    build:
      context: .
    restart: unless-stopped
    container_name: todo-php-apache
    volumes:
      - "./TODO:/var/www/html"
    ports:
      - "80:80"
    networks:
      - todo-network

  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: todo-db
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: qwerty123
       MYSQL_DATABASE: todo_db
       MYSQL_USER: test_user
       MYSQL_PASSWORD: test_pass
    networks:
      - todo-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    ports:
      - "8001:80"
    container_name: todo-pma
    environment:
      PMA_HOST: db
      PMA_USER: test_user
      PMA_PASSWORD: test_pass
      PMA_PORT: 3306
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
